### ISSUE TITLE
Spaces in label deletes keyring

### ISSUE THREAD

**Issue by Mozzo1000** [gabrielchiconi/sw#15]
If `sw` returns `This action requires 2 arguments!`, it makes the keyring.json file be cleared and every entry will be replaced by "null"

As an extra, now that the keyring.json is malformed, `sw list` returns NoneType error.
```
Traceback (most recent call last):
  File "/home/REDACTED/.local/bin/sw", line 185, in <module>
    main()
  File "/home/REDACTED/.local/bin/sw", line 181, in main
    commands[command](*args)
  File "/home/REDACTED/.local/bin/sw", line 32, in open_keyring_fn
    result = fn(*args, **kwargs, keyring=keyring)
  File "/home/REDACTED/.local/bin/sw", line 75, in list_keys
    for key, addr in keyring.items():
AttributeError: 'NoneType' object has no attribute 'items'
```

## To reproduce
**Add a entry :**
`sw add prod 192.168.1.1`

 **Add another entry with a space instead of a label**
<pre>
sw add    192.168.1.1
</pre>

**Comment by fizzy-drinks** [comment]
[Line 44](https://github.com/gabrielchiconi/sw/blob/master/bin/sw#L44) should return `keyring` instead of `None`, which is currently causing the bug if an action decorated with `@open_keyring(write=True)` fails to meet the required amount of arguments.

As an aside, a shell will ignore any amount of spaces, so what you did:

```sw add   192.168.1.1```

is identical to

```sw add 192.168.1.1```

or to any amount of spaces for that matter.
